// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSVL8Q6SdFuHGQxwK-gsPG7pFS_rCGrhs',
    appId: '1:777575333399:android:197c1a365da07b41662652',
    messagingSenderId: '777575333399',
    projectId: 'social-game-test',
    storageBucket: 'social-game-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKkvsnTVH_goh2tmfFwnGxsUG_RuH1bHs',
    appId: '1:777575333399:ios:a69a69e30530fc30662652',
    messagingSenderId: '777575333399',
    projectId: 'social-game-test',
    storageBucket: 'social-game-test.appspot.com',
    androidClientId: '777575333399-3p44o01r2jdnttnp3gufgfbg4vrvevec.apps.googleusercontent.com',
    iosClientId: '777575333399-t9trr724uiccvuasqllaed6opngihufu.apps.googleusercontent.com',
    iosBundleId: 'io.ocal.owogametest.socialgame',
  );
}
